### ISSUE TITLE
ImportError: cannot import name getargspec

### ISSUE THREAD

**Issue by iris-garden** [iris-garden/test-process#1424]
<h2>tpoterba said:</h2>
<p>The author of the <code>decorator</code> module pushed a new version to PyPI a few days ago which removed functionality from the module without updating the major version. This means that <strong>decorator 4.3.0 will not work with Hail 0.1.</strong></p>
<p>To fix this, use:</p>

```python
pip install decorator==4.2.1

```

<h2>tpoterba said:</h2>
<p>An update: Current Hail 0.2 is compatible with later versions of <code>decorator</code></p>
