### ISSUE TITLE
Running hail on AWS EMR

### ISSUE THREAD

**Issue by iris-garden** [iris-garden/test-process#1423]
<h2>chirag_lakhani said:</h2>
<p>Hi,</p>
<p>I apologize if this is a dumb question but I’m a Hail newbie.  I am trying to simply run Hail on Amazon EMR.  I have setup a small EMR cluster using emr-5.13.0 which has Spark 2.3.0.  Following some scripts built by Amazon I logged into the master node and ran the following</p>
<p>HAIL_VERSION=“0.1”<br>
SPARK_VERSION=“2.3.0”</p>
<p>/usr/bin/sudo pip install decorator</p>
<p>sudo yum update -y<br>
sudo yum install g++ cmake git -y</p>
<p>git clone <a href="https://github.com/broadinstitute/hail.git" class="inline-onebox" rel="noopener nofollow ugc">GitHub - hail-is/hail: Cloud-native genomic dataframes and batch computing</a><br>
cd hail/<br>
git checkout $HAIL_VERSION<br>
./gradlew -Dspark.version=$SPARK_VERSION shadowJar archiveZip</p>
<p>cp $PWD/build/distributions/hail-python.zip $HOME<br>
cp $PWD/build/libs/hail-all-spark.jar $HOME</p>
<p>echo “” >> $HOME/.bashrc<br>
echo “export PYTHONPATH=${PYTHONPATH}:$HOME/hail-python.zip” >> $HOME/.bashrc</p>
<p>afterwards I tried to start pyspark using the following command:</p>
<p>pyspark --jars hail-all-spark.jar --py-files hail-python.zip</p>
<p>as I try to import Hail I get the following error</p>
<blockquote>
<blockquote>
<blockquote>
<p>sc.addFile(‘/home/hadoop/hail-all-spark.jar’)<br>
sc.addPyFile(‘/home/hadoop/hail-python.zip’)<br>
from hail import *<br>
Traceback (most recent call last):<br>
File “”, line 1, in <br>
File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/<strong>init</strong>.py”, line 1, in </p>
</blockquote>
</blockquote>
</blockquote>

```python
#

```

<p>File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/expr.py”, line 3, in <br>
File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/representation/<strong>init</strong>.py”, line 1, in <br>
#<br>
File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/representation/variant.py”, line 2, in <br>
File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/typecheck/<strong>init</strong>.py”, line 1, in <br>
#<br>
File “/mnt/tmp/spark-7970940d-c351-48d6-be82-1c2cb4647b24/userFiles-7fa2e70a-b1b5-48a3-bcf8-fba119200a8a/hail-python.zip/hail/typecheck/check.py”, line 1, in <br>
ImportError: cannot import name getargspec</p>
<blockquote>
<blockquote>
<blockquote>
<p>hc = HailContext(sc)<br>
Traceback (most recent call last):<br>
File “”, line 1, in <br>
NameError: name ‘HailContext’ is not defined</p>
</blockquote>
</blockquote>
</blockquote>
<p>Could someone explain why this is happening?</p>

<h2>tpoterba said:</h2>
<p>Just made a post about this:</p>
<a href="http://discuss.hail.is/t/importerror-cannot-import-name-getargspec/468">ImportError: cannot import name getargspec</a><blockquote>
    The author of the decorator module pushed a new version to PyPI a few days ago which removed functionality from the module without updating the major version. This means that decorator 4.3.0 will not work with Hail 0.1. 
To fix this, use: 
pip install decorator==4.2.1
  </blockquote>

<h2>tpoterba said:</h2>
<p>however, I don’t think Hail 0.1 is compatible with Spark 2.3.0 anyway. You should use the 0.2 beta version if you’re just getting started!</p>

<h2>chirag_lakhani said:</h2>

<blockquote>
<p>pip install decorator==4.2.1</p>
</blockquote>

<p>Thanks so much, yes I just tried it but am realizing that pyspark on EMR uses python 2.7, however you guys use Python 3.6.  Do you know how one would change that?</p>

<h2>tpoterba said:</h2>
<p>here’s something that might help: <a href="https://medium.com/@datitran/quickstart-pyspark-with-anaconda-on-aws-660252b88c9a">https://medium.com/@datitran/quickstart-pyspark-with-anaconda-on-aws-660252b88c9a</a></p>

<h2>chirag_lakhani said:</h2>
<p>This is great, thanks so much!</p>

<h2>atebbe said:</h2>
<p>If you use EMR release 5.12.1 you can install python  3.6 as a bootstrap action on the cluster.</p>
